# Generated by Django 5.2.1 on 2025-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Utworzenie'), ('deleted', 'Usunięcie'), ('commented', 'Komentarz'), ('updated', 'Edycja')], default='created', max_length=20),
        ),
    ]
