# Generated by Django 5.2.1 on 2025-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
    ]
