# Generated by Django 5.2.1 on 2025-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activity_source_user_alter_activity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('W toku', 'W toku'), ('Ukończone', 'Ukończone')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
