# Generated by Django 5.2.1 on 2025-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'W toku'), ('completed', 'Ukończone'), ('overdue', 'Po terminie'), ('upcoming', 'Nadchodzące')], default='in_progress', max_length=20),
        ),
    ]
