# Generated by Django 5.2.1 on 2025-06-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
    ]
