# Generated by Django 5.1.7 on 2025-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_userprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='user_task_attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'W toku'), ('completed', 'Ukończone'), ('overdue', 'Po terminie'), ('upcoming', 'Nadchodzące'), ('no_deadline', 'Bez deadlinu')], default='upcoming', max_length=20),
        ),
    ]
